<?php

use App\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker\Factory::create();
        DB::table('users')->insert([
            [
                'first_name' => 'Ruben',
                'last_name' => 'Matos',
                'email' => 'ruben@admin.com',
                'password' => bcrypt('000000'),
                'zip_code' => '00000000',
                'address' => 'Rua Fransisco Veira de Paiva',
                'street_number' => '191',
                'phone_1' => '34996427629',
                'phone_2' => null,
                'phone_landline' => '3432240507',
                'whatsapp_number' => '34996427629',
                'nationality' => 'Portuguese',
                'date_of_birth' => '19021985',
                'gender' => 0,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => null,
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 1,
                'cpf' => '01800920652',
                'personal_id_number' => '65468481',
                'dentist_unique_identifier' => '45848',
                'additional_info' => null,
            ],
            [
                'first_name' => 'Mariana',
                'last_name' => 'de Oliveira',
                'email' => 'mariana.oliveira@email.com',
                'password' => bcrypt('mari2020'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => '34991390475',
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 1,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '321654',
                'dentist_unique_identifier' => "4984984984",
                'additional_info' => null,
            ]
            ,
            [
                'first_name' => 'Luciene',
                'last_name' => 'de Oliveira',
                'email' => 'Luciene@email.com',
                'password' => bcrypt('123456'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => null,
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 1,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '89498498',
                'dentist_unique_identifier' => "32181651",
                'additional_info' => null,
            ]
            ,
            [
                'first_name' => 'Daiane',
                'last_name' => 'Divina',
                'email' => 'Daiane_denize_lopez@hotmail.com',
                'password' => bcrypt('123456'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => null,
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 1,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '48651265',
                'dentist_unique_identifier' => "1895195",
                'additional_info' => null,
            ]
            ,
            [
                'first_name' => 'Patricia',
                'last_name' => 'Sousa',
                'email' => 'Patricia@email.com',
                'password' => bcrypt('123456'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => null,
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 1,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '45651618848',
                'dentist_unique_identifier' => '78577',
                'additional_info' => null,
            ]
            ,
            [
                'first_name' => 'Raymara',
                'last_name' => '',
                'email' => 'Raymara@email.com',
                'password' => bcrypt('123456'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => null,
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 1,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '4556546468',
                'dentist_unique_identifier' => '5685165',
                'additional_info' => null,
            ]
            ,
            [
                'first_name' => 'Carla',
                'last_name' => 'Reis Machado',
                'email' => 'Carlaremac@gmail.com',
                'password' => bcrypt('123456'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => null,
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 1,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '48168181',
                'dentist_unique_identifier' => "594516",
                'additional_info' => null,
            ]
            ,
            [
                'first_name' => 'Cristielen',
                'last_name' => '',
                'email' => 'Cristielen@email.com',
                'password' => bcrypt('123456'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => null,
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 1,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '1561651984',
                'dentist_unique_identifier' => "0321315",
                'additional_info' => null,
            ]
            ,
            [
                'first_name' => 'Rodrigo',
                'last_name' => 'Reis',
                'email' => 'Rodrigo@email.com',
                'password' => bcrypt('123456'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => null,
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 0,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '564684894',
                'dentist_unique_identifier' => "8951905",
                'additional_info' => null,
            ]
            ,
            [
                'first_name' => 'Aline',
                'last_name' => '',
                'email' => 'Aline@email.com',
                'password' => bcrypt('123456'),
                'zip_code' => null,
                'address' => null,
                'street_number' => null,
                'phone_1' => null,
                'phone_2' => null,
                'phone_landline' => null,
                'whatsapp_number' => null,
                'nationality' => null,
                'date_of_birth' => null,
                'gender' => 0,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => 'visa',
                'card_lasts_for' => '0000',
                'earn_percentage' => '0',
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 2,
                'cpf' => null,
                'personal_id_number' => '65168486',
                'dentist_unique_identifier' => "9561506",
                'additional_info' => null,
            ],
            [
                'first_name' => 'Marko',
                'last_name' => 'Dupor',
                'email' => 'marko@admin.com',
                'password' => bcrypt('123456'),
                'zip_code' => $faker->countryCode,
                'address' => $faker->address,
                'street_number' => $faker->numberBetween(1, 100),
                'phone_1' => $faker->phoneNumber,
                'phone_2' => $faker->phoneNumber,
                'phone_landline' => $faker->phoneNumber,
                'whatsapp_number' => $faker->phoneNumber,
                'nationality' => $faker->word,
                'date_of_birth' => $faker->dateTimeThisCentury,
                'gender' => 0,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => $faker->word,
                'card_lasts_for' => $faker->dateTimeThisCentury,
                'earn_percentage' => $faker->numberBetween(0, 100),
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 1,
                'cpf' => $faker->word,
                'personal_id_number' => $faker->word,
                'dentist_unique_identifier' => $faker->word,
                'additional_info' => $faker->word,
            ],
            [
                'first_name' => 'Ed',
                'last_name' => 'Enzo',
                'email' => 'ed@admin.com',
                'password' => bcrypt('123456'),
                'zip_code' => $faker->countryCode,
                'address' => $faker->address,
                'street_number' => $faker->numberBetween(1, 100),
                'phone_1' => $faker->phoneNumber,
                'phone_2' => $faker->phoneNumber,
                'phone_landline' => $faker->phoneNumber,
                'whatsapp_number' => $faker->phoneNumber,
                'nationality' => $faker->word,
                'date_of_birth' => $faker->dateTimeThisCentury,
                'gender' => 0,
                'stripe_id' => $faker->bankAccountNumber,
                'card_brand' => $faker->word,
                'card_lasts_for' => $faker->dateTimeThisCentury,
                'earn_percentage' => $faker->numberBetween(0, 100),
                'is_whatsapp_number_public' => true,
                'resident_in_clinic' => true,
                'accepts_after_hour_calls' => true,
                'clinic_id' => 1,
                'cpf' => $faker->word,
                'personal_id_number' => $faker->word,
                'dentist_unique_identifier' => $faker->word,
                'additional_info' => $faker->word,
            ]
        ]);

        User::find(1)->roles()->attach([1]);
        User::find(2)->roles()->attach([3]);
        User::find(3)->roles()->attach([2, 3]);
        User::find(4)->roles()->attach([3]);
        User::find(5)->roles()->attach([7]);
        User::find(6)->roles()->attach([7]);
        User::find(7)->roles()->attach([3]);
        User::find(8)->roles()->attach([3]);
        User::find(9)->roles()->attach([3]);
        User::find(10)->roles()->attach([3]);
        User::find(11)->roles()->attach([1]);
        User::find(12)->roles()->attach([10]);

        User::find(2)->specialties()->attach([12]);
        User::find(2)->specialties()->attach([2]);
        User::find(3)->specialties()->attach([2]);
        User::find(4)->specialties()->attach([8]);
        User::find(4)->specialties()->attach([2]);
        User::find(7)->specialties()->attach([11]);
        User::find(7)->specialties()->attach([2]);
        User::find(8)->specialties()->attach([2]);
        User::find(9)->specialties()->attach([12]);
        User::find(9)->specialties()->attach([2]);
        User::find(10)->specialties()->attach([2]);

    }
}
