<?php

use App\User;
use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker\Factory::create();
        DB::table('users')->insert([
            [
                'first_name'         => $faker->firstName,
                'last_name'          => $faker->lastName,
                'email'              => 'admin@admin.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => $faker->countryCode,
                'address'            => $faker->address,
                'street_number'      => $faker->numberBetween(1, 100),
                'phone_1'            => $faker->phoneNumber,
                'phone_2'            => $faker->phoneNumber,
                'phone_landline'     => $faker->phoneNumber,
                'whatsapp_number'    => $faker->phoneNumber,
                'nationality'        => $faker->word,
                'date_of_birth'      => $faker->dateTimeThisCentury,
                'gender'             => 0,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => $faker->word,
                'card_lasts_for'     => $faker->dateTimeThisCentury,
                'thai_ends_at'       => $faker->dateTimeThisCentury,
                'honors'             => $faker->sentence(5),
                'percentage'         => $faker->numberBetween(0, 100),
                'value'              => $faker->numberBetween(50, 100),
                'earn_percentage'    => $faker->numberBetween(0, 100),
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 1,
                'cpf'                => $faker->word,
                'rg'                 => $faker->word,
                'cro'                => $faker->word,
                'observation'        => $faker->word,
            ],
            [
                'first_name'         => 'Mariana',
                'last_name'          => 'de Oliveira',
                'email'              => 'mariana.oliveira@email.com',
                'password'           => bcrypt('mari2020'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => '34991390475',
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 1,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => "0",
                'observation'        => null,
            ]
            ,
            [
                'first_name'         => 'Luciene',
                'last_name'          => 'de Oliveira',
                'email'              => 'Luciene@email.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => null,
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 1,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => "0",
                'observation'        => null,
            ]
            ,
            [
                'first_name'         => 'Daiane',
                'last_name'          => 'Divina',
                'email'              => 'Daiane_denize_lopez@hotmail.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => null,
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 1,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => "0",
                'observation'        => null,
            ]
            ,
            [
                'first_name'         => 'Patricia',
                'last_name'          => 'Sousa',
                'email'              => 'Patricia@email.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => null,
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 1,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => null,
                'observation'        => null,
            ]
            ,
            [
                'first_name'         => 'Raymara',
                'last_name'          => '',
                'email'              => 'Raymara@email.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => null,
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 1,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => null,
                'observation'        => null,
            ]
            ,
            [
                'first_name'         => 'Carla',
                'last_name'          => 'Reis Machado',
                'email'              => 'Carlaremac@gmail.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => null,
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 1,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => "0",
                'observation'        => null,
            ]
            ,
            [
                'first_name'         => 'Cristielen',
                'last_name'          => '',
                'email'              => 'Cristielen@email.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => null,
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 1,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => "0",
                'observation'        => null,
            ]
            ,
            [
                'first_name'         => 'Rodrigo',
                'last_name'          => 'Reis',
                'email'              => 'Rodrigo@email.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => null,
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 0,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => "0",
                'observation'        => null,
            ]
            ,
            [
                'first_name'         => 'Aline',
                'last_name'          => '',
                'email'              => 'Aline@email.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => null,
                'address'            => null,
                'street_number'      => null,
                'phone_1'            => null,
                'phone_2'            => null,
                'phone_landline'     => null,
                'whatsapp_number'    => null,
                'nationality'        => null,
                'date_of_birth'      => null,
                'gender'             => 0,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => 'visa',
                'card_lasts_for'     => '0000',
                'thai_ends_at'       => '',
                'honors'             => null,
                'percentage'         => '0',
                'value'              => '0',
                'earn_percentage'    => '0',
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 2,
                'cpf'                => null,
                'rg'                 => null,
                'cro'                => "0",
                'observation'        => null,
            ],
            [
                'first_name'         => $faker->firstName,
                'last_name'          => $faker->lastName,
                'email'              => 'admin2@admin.com',
                'password'           => bcrypt('123456'),
                'zip_code'           => $faker->countryCode,
                'address'            => $faker->address,
                'street_number'      => $faker->numberBetween(1, 100),
                'phone_1'            => $faker->phoneNumber,
                'phone_2'            => $faker->phoneNumber,
                'phone_landline'     => $faker->phoneNumber,
                'whatsapp_number'    => $faker->phoneNumber,
                'nationality'        => $faker->word,
                'date_of_birth'      => $faker->dateTimeThisCentury,
                'gender'             => 0,
                'stripe_id'          => $faker->bankAccountNumber,
                'card_brand'         => $faker->word,
                'card_lasts_for'     => $faker->dateTimeThisCentury,
                'thai_ends_at'       => $faker->dateTimeThisCentury,
                'honors'             => $faker->sentence(5),
                'percentage'         => $faker->numberBetween(0, 100),
                'value'              => $faker->numberBetween(50, 100),
                'earn_percentage'    => $faker->numberBetween(0, 100),
                'uses_whatsapp'      => true,
                'resident_in_clinic' => true,
                'accept_calls'       => true,
                'clinic_id'          => 1,
                'cpf'                => $faker->word,
                'rg'                 => $faker->word,
                'cro'                => $faker->word,
                'observation'        => $faker->word,
            ]
        ]);

        User::find(1)->roles()->attach([1,3]);
        User::find(2)->roles()->attach([3]);
        User::find(3)->roles()->attach([2,3]);
        User::find(4)->roles()->attach([3]);
        User::find(5)->roles()->attach([7]);
        User::find(6)->roles()->attach([7]);
        User::find(7)->roles()->attach([3]);
        User::find(8)->roles()->attach([3]);
        User::find(9)->roles()->attach([3]);
        User::find(10)->roles()->attach([3]);

        User::find(2)->specialties()->attach([12]);
        User::find(2)->specialties()->attach([2]);
        User::find(3)->specialties()->attach([2]);
        User::find(4)->specialties()->attach([8]);
        User::find(4)->specialties()->attach([2]);
        User::find(7)->specialties()->attach([11]);
        User::find(7)->specialties()->attach([2]);
        User::find(8)->specialties()->attach([2]);
        User::find(9)->specialties()->attach([12]);
        User::find(9)->specialties()->attach([2]);
        User::find(10)->specialties()->attach([2]);

    }
}
